# Warning: these are all registered to sandbox applications setup by @jamiew
# Don't use in production! For testing/verification only and subject to change

google: # also used by the YouTube provider
  key: "379400648321.apps.googleusercontent.com"
  secret: "-OHDuK1rCJHU3HLqUjb-o8l9"
twitter:
  key: "gtYLGol7lhrqTpnDLCbnww"
  secret: "4IN5Ad6E0T0kSPwxlGlkYa4qx3Xd76iSUU3UMOX8a4"
facebook:
  key: "533786806693073"
  secret: "7192722f78493426268ef2f6878e9ec0"
